theme: jekyll-theme-slate
title: Meteor Deploy - The BASH script!
description: Bash script for easy Meteor.js deployment to remote server (Ubuntu with NGINX, Passenger) over SSH; needs remote server already configured.