#!/bin/bash

# STEPS:
# 
# 1.1 Ask for configuration file (see configuration file example)
# 1.2 If configuration file not used, ask for parameters
# 2. Build application bundle
# 3. Sign Android APK files
# 4. Upload new application bungle to remote server
# 5. Deploy uploaded bundle on remote server (using nginx/passenger on Ubuntu)

echo ""
echo ""
echo "Deploy your Meteor application to a remote server"
echo ""
echo ""

# Get the current folder path (full)
SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )

# Make all lib scripts executable
chmod +x -R ${SCRIPTPATH}/lib/*.sh

# Load configuration file
source "${SCRIPTPATH}/lib/load_config_file.sh"

meteor_deploy()
{
	echo ""
	echo "--== Meteor.js Deploy ==--"
	echo ""

	# MAIN MENU:
	echo "1. Deploy Meteor.js application"
	echo "2. Check local dependencies"
	echo "3. Check remote server dependencies"
	echo "4. Setup remote server"
	echo "5. Sign Android APKs (if needed)"
	echo "0. Exit (q)"
	echo ""

	read -r -p "Choose an option: " input

	echo ""
	echo ""

	case $input in
	    [1])
			# Build new app bundle
			source "${SCRIPTPATH}/lib/build_new_bundle.sh"

			# Upload app bundle to remote server
			source "${SCRIPTPATH}/lib/upload_application_bundle.sh"
			
			# Deploy app bundle on remote server
			source "${SCRIPTPATH}/lib/deploy_remote_bundle.sh"
		;;

		[2])
			# Install local system dependencies
			source "${SCRIPTPATH}/lib/install_local_dependencies.sh"
		;;

		[3])
			# Install remote system dependencies
			# 
			# 
			# 
			# source "${SCRIPTPATH}/lib/install_remote_dependencies.sh"

			echo ""
			echo "INFO: This feature is not yet implemented"

			meteor_deploy
		;;

		[4])
			# Setup remote server
			# 
			# 
			# 
			# source "${SCRIPTPATH}/lib/setup_remote_server.sh"

			echo ""
			echo "INFO: This feature is not yet implemented"

			meteor_deploy
		;;

		[5])
			# Sign Android APKs
			source "${SCRIPTPATH}/lib/sign_android_apks.sh"
		;;

		# [nN][oO]|[nN])
		# 	echo "Deployment canceled!"
		# ;;

		[qQ][uU][iI][tT]|[qQ]|[0])
			exit 1
		;;

	    *)
			echo "Invalid input..."
			meteor_deploy
		;;
	esac

	# END
}

meteor_deploy